"""Extract MFCC features and generate an Arduino-compatible C header.

Example:
	python vector.py input.wav --output mfcc_vector.h
"""

from pathlib import Path
import argparse

import librosa
import numpy as np


# MFCC parameters. Change these values to match the model used by the Arduino.
SAMPLE_RATE = 16000
N_MFCC = 13
N_FFT = 512
HOP_LENGTH = 160
WIN_LENGTH = 400
N_MELS = 40
FMIN = 20
FMAX = 8000


def extract_mfcc(audio_path: Path) -> np.ndarray:
	"""Load an audio file and return MFCCs as a flattened float32 vector."""
	audio, _ = librosa.load(audio_path, sr=SAMPLE_RATE, mono=True)
	if audio.size == 0:
		raise ValueError(f"Audio file is empty: {audio_path}")

	features = librosa.feature.mfcc(
		y=audio,
		sr=SAMPLE_RATE,
		n_mfcc=N_MFCC,
		n_fft=N_FFT,
		hop_length=HOP_LENGTH,
		win_length=WIN_LENGTH,
		n_mels=N_MELS,
		fmin=FMIN,
		fmax=min(FMAX, SAMPLE_RATE // 2),
	)
	return np.asarray(features, dtype=np.float32).reshape(-1)


def write_c_header(features: np.ndarray, output_path: Path, name: str) -> None:
	"""Write the feature vector as a C/C++ array for an Arduino sketch."""
	values = ", ".join(f"{value:.8f}f" for value in features)
	header = f"""// Generated by vector.py - do not edit manually.
#pragma once

#include <stddef.h>

const float {name}[{features.size}] = {{
	{values}
}};
const size_t {name}_length = {features.size};
"""
	output_path.write_text(header, encoding="utf-8")


def main() -> None:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("audio", type=Path, help="Input WAV/audio file")
	parser.add_argument("--output", type=Path, default=Path("mfcc_vector.h"))
	parser.add_argument("--name", default="mfcc_vector", help="C array name")
	args = parser.parse_args()

	if not args.audio.is_file():
		parser.error(f"Input file does not exist: {args.audio}")
	features = extract_mfcc(args.audio)
	write_c_header(features, args.output, args.name)
	print(f"Wrote {features.size} MFCC values to {args.output}")


if __name__ == "__main__":
	main()
